@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@eventId = 2f867caa-1e0e-40e2-b6cf-501556d9c278

### Create a new spot
# @name createSpot
POST http://{{host}}/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "A1"
}

###
@spotId = {{ createSpot.response.body.id }}

### Get all spots
GET http://{{host}}/events/{{eventId}}/spots

### Get one spot
GET http://{{host}}/events/{{eventId}}/spots/{{ spotId }}

### Update a spot
PATCH http://{{host}}/events/{{eventId}}/spots/{{ spotId }}
Content-Type: application/json

{
  "status": "reserved"
}

### Delete a spot
DELETE http://{{host}}/events/{{eventId}}/spots/{{ spotId }}
